### DISCUSSION TITLE
-spf to extract ip's from spf records

### DISCUSSION THREAD

**Discussion by brenocss** [projectdiscovery/dnsx#147] [General]
### Please describe your feature request:

`-spf` to extract ip's from spf records (includes,redirects,...)
- Reference : https://github.com/darkoperator/dnsrecon/blob/e1b742ea92c9e123d807601322748911d92cf727/dnsrecon.py#L99
### Describe the use case of this feature:
```zsh
echo gmail.com | dnsx -spf -json
```
```json
"spf_ip4": [
"35.190.247.0/24",
"64.233.160.0/19",
"66.102.0.0/20",
"66.249.80.0/20",
"72.14.192.0/18",
"74.125.0.0/16",
...,
]
```

**Comment by ehsandeep** [comment]
@brenocss instead of doing hardcoded parsing in dnsx, same can be achieved with template with nuclei.

```yaml
id: spf-fingerprint

info:
  name: SPF IP Fingerprint
  author: pdteam
  severity: info
  tags: dns,txt

dns:
  - name: "{{FQDN}}"
    type: TXT

    matchers:
      - type: regex
        regex:
          - "IN\tTXT"
          - "[0-9]{1,3}(?:\\.[0-9]{1,3}){0,3}/[0-9]+"
        condition: and

    extractors:
      - type: regex
        regex:
          - "[0-9]{1,3}(?:\\.[0-9]{1,3}){0,3}/[0-9]+"
```
